FROM quay.io/redhatqe/selenium-standalone:latest

USER 0

RUN microdnf update -y && \
    microdnf install -y nss-tools nss-sysinit && \
    modutil -fips true -dbdir /etc/pki/nssdb -force && \
    chown -R 0:0 /etc/pki/nssdb && \
    chmod 644 /etc/pki/nssdb/* && \
    microdnf clean all

USER 1001

