#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[[ -x /etc/vnc/xstartup ]] && exec /etc/vnc/xstartup
[[ -r $SELENIUM_HOME/.Xresources ]] && xrdb $SELENIUM_HOME/.Xresources

xsetroot -solid grey
fluxbox &
sleep 5
java -jar $SELENIUM_PATH -port $SELENIUM_PORT >> /proc/1/fd/1 2>&1
