name: Test

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build standalone image
        uses: redhat-actions/buildah-build@v2.5
        with:
          image: quay.io/redhatqe/selenium-standalone
          dockerfiles: standalone/Dockerfile
          context: standalone
          oci: true
